### ISSUE TITLE
Failed to import datadog_lambda

### ISSUE THREAD

**Issue by SamuelM333** [DataDog/datadog-lambda-layer-python#42] opened 2020-01-16 19:10 UTC
## Expected Behavior
Be able to use the `datadog_lambda`package when adding the Datadog lambda layer.

## Actual Behavior
The `datadog_lambda`package is not found and I get an import error.

## Steps to Reproduce the Problem

  1. Follow the [Amazon Lambda docs](https://docs.datadoghq.com/integrations/amazon_lambda/?tab=serverlessframework#installing-and-using-the-datadog-lambda-layer) 
  1. Use `serverless-plugin-datadog`
  1. Try to run the lambda. You should get an import error.
  1. Now add `datadog-lambda==0.11.0` to `requirements.txt` and try running the lambda again. No error this time.

## Specifications

  - Datadog Lambda Layer version: 11
  - Python version: 3.7
  
## Stacktrace
  
  ```
  [ERROR] Runtime.ImportModuleError: Unable to import module 'datadog_handlers/authorizer': No module named 'datadog_lambda'
  ```

**Comment by DarcyRaynerDD** [comment] 2020-01-31 16:24
Hi @SamuelM333 👋  Thanks for the report. It looks like the lambda layer wasn't actually being attached to your function. I tried to reproduce, but it seemed to work fine for me. Did you set the [addLayers](https://github.com/DataDog/serverless-plugin-datadog#all-options) option to `false`?

**Comment by SamuelM333** [comment] 2020-02-14 19:55
Hey, sorry for the delay. I have `addLayers: true` and I do have the layer attached. I tried upgrading from the layer version 11 to 13 and still have the issue.

**Comment by tianchu** [comment] 2020-02-25 14:59
@SamuelM333 if you are already using the serverless framework plugin and have addLayers:true, then you shouldn't need to add `datadog-lambda` to your requirements.txt (the plugin already add datadog-lambda through the layer). I don't think this should cause the issue, but it's worth try removing it.

If that doesn't help, do you mind copying us the content of your handler function code from Lambda console? If it's too big and not displaying in the IDE, then you have to download the zip. The reason we ask this is because, the serverless plugin modifies/wraps your original handler function when you run sls deploy, and we need to see the code of your wrapped handler function (where that stacktrace was generated) to see what's wrong.

Thanks!

**Comment by tianchu** [comment] 2020-03-20 15:56
@SamuelM333 I'm going to close this issue now, assuming you have already fixed the issue. If not, feel free to reopen with the information I mentioned in the previous comment.

**Closed by tianchu** 2020-03-20 15:56 UTC

**Comment by rishisshah** [comment] 2022-02-16 22:39
@SamuelM333 Having the same issue as you right now, were you ever able to get it working? If so, what was your approach?
